// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngfzeebvgmxefgfjdoaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nZnplZWJ2Z214ZWZnZmpkb2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODcyMTIsImV4cCI6MjA1OTI2MzIxMn0.I9958J0CHFDSPQT0vBueud9xUys_6VyQ_u-6KIhE630";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);